dwm_status: pango is optional

diff --git a/dwm/dot-local/share/dwm/scripts/dwm_status b/dwm/dot-local/share/dwm/scripts/dwm_status
--- a/dwm/dot-local/share/dwm/scripts/dwm_status
+++ b/dwm/dot-local/share/dwm/scripts/dwm_status
@@ -2,29 +2,37 @@
 
 # set -x
 
-date_and_time(){
-    date '+%b %e %a %_Hh%M'
+print_usage() {
+	printf "$(basename "${0}") [-h] [-p]\\n"
 }
 
-format_cpu_load(){
-    printf '%6.2f%%\n' ${1}
+pango=""
+while getopts ":hp" opt
+do
+    case ${opt} in
+        h)
+            print_usage
+            exit
+            ;;
+        p)
+            pango="yes"
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+    esac
+done
+shift $((OPTIND - 1))
+
+date_and_time(){
+    date '+%b %e %a %_Hh%M'
 }
 
 # From i3blocks
 cpu_load(){
     idle=$(mpstat 1 1 | sed -n 's/^Average.* \([0-9]\+\.[0-9]\+\)/\1/p')
-    load=$(echo "100-${idle}" | bc -l)
-    if [ -n "${load%.*}" ] && [ ${load%.*} -gt 80 ]
-    then
-        echo "<span color='red'>$(format_cpu_load ${load})</span>"
-        exit
-    fi
-    if [ -n "${load%.*}" ] && [ ${load%.*} -gt 50 ]
-    then
-        echo "<span color='yellow'>$(format_cpu_load ${load})</span>"
-        exit
-    fi
-    format_cpu_load ${load}
+    echo "100-${idle}" | bc -l
 }
 
 # From i3blocks
@@ -76,16 +84,44 @@ internet3(){
 internet(){
     if ! internet1 && ! internet2 && ! internet3
     then
-        echo "<span color='yellow'>*</span>"
-        exit
+        echo "*"
+        exit 1
     fi
-    echo "<span color='#89CFF0'>@</span>"
 }
 
 # Killing all other instances
 pid=${$}
 pgrep -f '/bin/sh .*\.local/share/dwm/scripts/dwm_status$' \
     | grep -v ${pid} | xargs -r kill -9
+
+pango_format_cpu_load(){
+    load=${1}
+    if [ -n "${cpu_load%.*}" ] && [ ${cpu_load%.*} -gt 80 ]
+    then
+        echo "<span color='red'>${load}</span>"
+        exit
+    fi
+    if [ -n "${cpu_load%.*}" ] && [ ${cpu_load%.*} -gt 50 ]
+    then
+        echo "<span color='yellow'>${load}</span>"
+        exit
+    fi
+    echo "${load}"
+}
+
+pango(){
+    [ -n "${internet}" ] && internet="<span color='yellow'>${internet}</span>"
+    [ -z "${internet}" ] && internet="<span color='#89CFF0'>@</span>"
+    pango_cpu_load="$(pango_format_cpu_load "$(printf '%6.2f%%' ${cpu_load})")"
+    printf ' %s  [%6s]  %5s  %s  %s ' \
+       "${internet}" ${hdd_info} "${memory_info}" "${pango_cpu_load}" "${date_and_time}"
+}
+
+regular(){
+    [ -z "${internet}" ] && internet="@"
+    printf ' %s  [%6s]  %5s  %6.2f%%  %s ' \
+       "${internet}" ${hdd_info} "${memory_info}" ${cpu_load} "${date_and_time}"
+}
 
 status=""
 
@@ -102,10 +138,11 @@ do
     ([ -z "${status}" ] || [ $((seconds%10)) -eq 0 ]) && internet="$(internet)"
     ([ -z "${status}" ] || [ $((seconds%20)) -eq 0 ]) && hdd_info=$(hdd_info)
     ([ -z "${status}" ] || [ $((seconds%10)) -eq 0 ]) && memory_info="$(memory_info)"
-    ([ -z "${status}" ] || [ $((seconds%5))  -eq 0 ]) && cpu_load="$(cpu_load)"
+    ([ -z "${status}" ] || [ $((seconds%5))  -eq 0 ]) && cpu_load=$(cpu_load)
     ([ -z "${status}" ] || [ $((seconds%60)) -eq 0 ]) && date_and_time="$(date_and_time)"
-    status="$(printf ' %s  [%6s]  %5s  %s  %s ' \
-       "${internet}" ${hdd_info} "${memory_info}" "${cpu_load}" "${date_and_time}")"
+
+    [ -n "${pango}" ] && status="$(pango)" || status="$(regular)"
+
     xsetroot -name "${status}"
     sleep 4
 done
